# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dt_fast <- function(y, mu, s, nu) {
    .Call('_fastStudentT_dt_fast', PACKAGE = 'fastStudentT', y, mu, s, nu)
}

studentTEM <- function(y, nu, niter) {
    .Call('_fastStudentT_studentTEM', PACKAGE = 'fastStudentT', y, nu, niter)
}

